### ISSUE TITLE
Ruby 2.0.0 crash (iconv isn't there anymore)

### ISSUE THREAD

**Issue by jyrkij** [francois/piston#11]
Here's the trace:

```
/Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- iconv (LoadError)
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-2.3.18/lib/active_support/inflector.rb:3:in `<top (required)>'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-2.3.18/lib/active_support/core_ext/integer/inflections.rb:1:in `<top (required)>'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-2.3.18/lib/active_support/core_ext/integer.rb:2:in `<top (required)>'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-2.3.18/lib/active_support/core_ext.rb:8:in `block in <top (required)>'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-2.3.18/lib/active_support/core_ext.rb:8:in `each'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-2.3.18/lib/active_support/core_ext.rb:8:in `<top (required)>'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-2.3.18/lib/active_support.rb:56:in `<top (required)>'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/piston-2.0.10/lib/piston/cli.rb:2:in `<top (required)>'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/gems/piston-2.0.10/bin/piston:5:in `<top (required)>'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/bin/piston:23:in `load'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/bin/piston:23:in `<main>'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/jyrkililja/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
```

http://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released/ says:

> Iconv was removed, which had already been deprecated when M17N was introduced in ruby 1.9. Use String#encode, etc. instead.

Any idea how much work this'd be and when it'd be adressed?

**Comment by felixbuenemann** [comment]
You can add gem "iconv", :platform => :mri_20 to your Gemfile.

**Comment by alexandre-mbm** [comment]
@felixbuenemann, `gem install iconv --platform=mri_20` does not work on Windows.

```
C:\>ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
```

**Comment by felixbuenemann** [comment]
@alexandre-mbm Unless you have the iconv library installed I doubt it would. No idea if iconv is even available on win32. If you want to save yourself a lot of headaches, switch to linux or mac os x.

**Comment by alexandre-mbm** [comment]
I got:

```
C:\> cd C:\DevKit
C:\> msys.bat
$ wget http://packages.openknapsack.org/libiconv/libiconv-1.14-x86-windows.tar.lzma
$ 7z x libiconv-1.14-x86-windows.tar.lzma
$ 7z x -olibiconv libiconv-1.14-x86-windows.tar
$ rm libiconv-1.14-x86-windows.tar*
$ cd /c/dev/libiconv
$ gem install iconv --platform=ruby -- --with-iconv-dir=/c/dev/libiconv
```

I had:

```
C:\>iconv --version
iconv (GNU libiconv 1.11)
Copyright (C) 2000-2002 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Bruno Haible.
```

@felixbuenemann, I use GNU/Linux but I want to try Ruby on windows for the sake of portability.

**Comment by felixbuenemann** [comment]
Btw. The platform hint is only for bundler, no need to pass it to gem install. On ruby 2.1 you should probably use mri_21 not mri_20.
