### ISSUE TITLE
cannot show status

### ISSUE THREAD

**Issue by grosser** [francois/piston#3]
```
piston import git://github.com/grosser/parallel_specs.git
piston status --> nothing
piston status parallel_specs/
DEPRECATION WARNING: require "activesupport" is deprecated and will be removed in Rails 3. Use require "active_support" instead.. (called from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/activesupport.rb:2)
/usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/git/working_copy.rb:142:in `last_changed_revision': undefined method `[]' for nil:NilClass (NoMethodError)
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/git/working_copy.rb:142:in `chdir'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/git/working_copy.rb:142:in `last_changed_revision'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/git/working_copy.rb:114:in `locally_modified'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/commands/status.rb:22:in `run'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/commands/status.rb:17:in `each_pair'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/commands/status.rb:17:in `run'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/commands/status.rb:42:in `start'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/commands/status.rb:40:in `each'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/commands/status.rb:40:in `start'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/cli.rb:67:in `start'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/lib/piston/cli.rb:121
from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /usr/local/lib/ruby/gems/1.8/gems/piston-2.0.7/bin/piston:5
from /usr/local/bin/piston:19:in `load'
from /usr/local/bin/piston:19
```

**Comment by francois** [comment]
See 2.0.8
