### ISSUE TITLE
Tests fail for piston 2.0.8

### ISSUE THREAD

**Issue by graaff** [francois/piston#4]
When trying to run the tests for piston 2.0.8 I get the following failures:

  1) Failure:
test_cloning_head_finds_head_commit(Piston::Git::TestGitCommitCheckout)
    [./lib/piston/git/commit.rb:54:in `checkout_to'
     ./lib/piston/git/commit.rb:51:in`checkout_to'
     ./test/unit/git/commit/test_checkout.rb:28:in `test_cloning_head_finds_head_commit'
     /var/tmp/portage/dev-ruby/piston-2.0.8/work/ruby18/piston-2.0.8/test/test_helper.rb:61:in`run']:
unexpected invocation: Piston::Revision(git://a.repos.com/project.git@master).git(:checkout, '-b', 'my-master', 'origin/master')
unsatisfied expectations:
- expected exactly once, not yet invoked: Piston::Revision(git://a.repos.com/project.git@master).git(:log, '-n', '1')
- expected exactly once, not yet invoked: Piston::Revision(git://a.repos.com/project.git@master).git(:checkout, '-b', 'my-master', 'master')
  satisfied expectations:
- allowed any number of times, already invoked 8 times: #Mock:repos.url(any_parameters)
- expected exactly once, already invoked once: Piston::Revision(git://a.repos.com/project.git@master).git(:clone, 'git://a.repos.com/project.git', #Pathname:0x7fcb48076cd0)
- expected exactly once, already invoked once: Dir.chdir(#Pathname:0x7fcb48076cd0)
  
  2) Failure:
  default_test(Piston::TestCase)
  [/usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in `__send__'
   /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in`run'
   /var/tmp/portage/dev-ruby/piston-2.0.8/work/ruby18/piston-2.0.8/test/test_helper.rb:61:in `run']:
  No tests were specified.

**Comment by graaff** [comment]
Still a problem in piston 2.0.9

**Comment by graaff** [comment]
Still a problem in piston 2.0.10
